apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xd-cloud-app-monitor-v2
  namespace: monitoring-cloud-app-v2
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cloud-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
