name: Build Docker Image and Push to Docker Registry

on:
  push:
    branches: [feature/last-adjustments]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Project version
        id: project-version
        run: |
          VERSION=$(./gradlew printVersion --quiet | tail -n 1)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64 # for M1 chip
          tags: katzex/cloud-app:${{ steps.project-version.outputs.version }}
          file: Dockerfile
          build-args: |
            VERSION=${{ steps.project-version.outputs.version }}

      - name: Image details
        run: |
          echo "Pushed image digest: ${{ steps.docker-build-push.outputs.digest }}"
          echo "Image tag: katzex/cloud-app:${{ steps.project-version.outputs.version }}"